spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehousedb
    username: admin
    password: Abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# =================================
# Client Secret
# =================================
jwt:
  clientSecret: ARROWPROJECTMGMTEAPP

# =================================
# Corss Filter
# =================================
gui:
  protocol: http
  host: localhost
  port: 4200

server:
  servlet:
    context-path: /
  port: 8081
    
